<a href="https://colab.research.google.com/github/Karthik0704/numpy-and-pandas/blob/main/numpy_and_panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#creating numpy
#creating single dimension array
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [ ]:
#creating numpy
#creating two dimension array
import numpy as np
n2=np.array([[10,20,30,40],[40,60,70,80]])
n2

array([[10, 20, 30, 40],
       [40, 60, 70, 80]])

In [ ]:
type(n2)

numpy.ndarray

In [ ]:
#initiliazing numpy arrays with 0
import numpy as np
n1=np.zeros((1,2))#here 1,2 refers that this will be 1 cross 2 matrix\
n1

array([[0., 0.]])

In [ ]:
#initiliazing numpy arrays with 0
import numpy as np
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#initiliazing numpy array with same numbers
import numpy as np
n1=np.full((3,3),100)  # here full is used to make same elements in matrix
n1

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [ ]:
# assigning ranges
import numpy as np
n1=np.arange(10,20) # here 10,20 will be the range and it includes 10 and excludes 20
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# assigning ranges
import numpy as np
n1=np.arange(10,20,2) # here 10,20 will be the range and it includes 10 and excludes 20 and 2 refers to the step between the two range
n1

array([10, 12, 14, 16, 18])

In [ ]:
# Initiliazing array with random numbers
import numpy as np
n1=np.random.randint(10,200,20)  # here 20 will be the number of random elements that shouls be displayed
n1

array([152, 150, 152,  52,  78,  47, 186,  10, 151, 139,  87,  23, 135,
       147, 158, 129, 188,  37,  79, 139])

In [ ]:
# To check thr order of matrix and to change it
import numpy as np
n2=np.array([[10,20,30,40],[40,60,70,80]])
n2.shape
n2

array([[10, 20, 30, 40],
       [40, 60, 70, 80]])

In [ ]:
n2.shape=(4,2) # This "shape" helps in changing the order of array
n2.shape
n2

array([[10, 20],
       [30, 40],
       [40, 60],
       [70, 80]])

In [ ]:
#joining numpy arrays using vstac() , hstack() and columnstack() to arrange the array vertically,horizontally and column wise respectively
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n2,n1))


array([[40, 50, 60],
       [10, 20, 30]])

In [ ]:
#joining numpy arrays using vstac() , hstack() and columnstack() to arrange the array vertically,horizontally and column wise respectively
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.hstack((n1,n2))


array([10, 20, 30, 40, 50, 60])

In [ ]:
#joining numpy arrays using vstac() , hstack() and column_stack() to arrange the array vertically,horizontally and column wise respectively
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.column_stack((n2,n1))


array([[40, 10],
       [50, 20],
       [60, 30]])

In [ ]:
#joining numpy arrays using vstac() , hstack() and column_stack() to arrange the array vertically,horizontally and column wise respectively
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.row_stack((n2,n1))


array([[40, 50, 60],
       [10, 20, 30]])

In [ ]:
# intersection and difference in array
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60,20,10])
np.intersect1d(n1,n2)

array([10, 20])

In [ ]:
# intersection and difference in array
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60,20,10])
np.setdiff1d(n1,n2)

array([30])

In [ ]:
# intersection and difference in array
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60,20,10])
np.setdiff1d(n2,n1)

array([40, 50, 60])

In [ ]:
#Addition of numpy arrays
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.sum([n1,n2])   # here this gives the sum of all the elements in the array

210

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.sum([n1,n2],axis=0) #This adds the column elements together and dispalys in a single row

array([50, 70, 90])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.sum([n1,n2],axis=1)  #this separetly adds all the row elements and displays in the row

array([ 60, 150])

In [ ]:
# Addding substracting multplying and dividing the array elements
import numpy as np
n1=np.array([10,20,30])
n1=n1+5                     # This add 5 to each elements and displays newly added elements
n1

array([15, 25, 35])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n1=n1-5                       # this substracts
n1

array([ 5, 15, 25])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n1=n1*5                       # this multiplies
n1

array([ 50, 100, 150])

In [ ]:
import numpy as np
n1=np.array([10,20,30,17])
n1=n1/5                           # This divides
n1   

array([2. , 4. , 6. , 3.4])

In [ ]:
# Find mean median and standard deviation for array elements
import numpy as np
n1=np.array([10,20,30,17])
np.mean(n1)

19.25

In [ ]:
import numpy as np
n1=np.array([10,20,30,17])
np.median(n1)

18.5

In [ ]:
import numpy as np
n1=np.array([10,20,30,17])
np.std(n1)

7.189401922274203

In [ ]:
#Saving and loading numpy arrayt
n1=np.array([22,33,55,78,95])
np.save('my_numpy',n1)               # This saves the array with given name
n2=np.load('my_numpy.npy')           # This reloads the savesd array with different name or object with specified
n2


array([22, 33, 55, 78, 95])